In [8]:
basics_url = "https://datasets.imdbws.com/title.basics.tsv.gz"

In [19]:
import pandas as pd
import numpy as np

In [20]:
basics = pd.read_csv(basics_url,sep='\t', low_memory=False)

In [21]:
basics = basics.dropna(subset=['runtimeMinutes', 'genres'])

In [22]:
basics = basics[basics['titleType']=='movie']

In [23]:
basics = basics[(basics['startYear'] > "1999") & (basics['startYear'] < "2022")]

In [24]:
# Exclude movies that are included in the documentary category.
is_documentary = basics['genres'].str.contains('documentary',case=False)
basics = basics[~is_documentary]

In [25]:
basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
11636,tt0011801,movie,Tötet nicht mehr,Tötet nicht mehr,0,2019,\N,\N,"Action,Crime"
15174,tt0015414,movie,La tierra de los toros,La tierra de los toros,0,2000,\N,60,\N
34790,tt0035423,movie,Kate & Leopold,Kate & Leopold,0,2001,\N,118,"Comedy,Fantasy,Romance"
61086,tt0062336,movie,The Tango of the Widower and Its Distorting Mi...,El Tango del Viudo y Su Espejo Deformante,0,2020,\N,70,Drama
67631,tt0069049,movie,The Other Side of the Wind,The Other Side of the Wind,0,2018,\N,122,Drama

In [26]:
basics.to_csv("Data/title_basics.csv.gz",compression='gzip',index=False)

In [27]:
basics = pd.read_csv("Data/title_basics.csv.gz", low_memory = False)
basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0011801,movie,Tötet nicht mehr,Tötet nicht mehr,0,2019,\N,\N,"Action,Crime"
1,tt0015414,movie,La tierra de los toros,La tierra de los toros,0,2000,\N,60,\N
2,tt0035423,movie,Kate & Leopold,Kate & Leopold,0,2001,\N,118,"Comedy,Fantasy,Romance"
3,tt0062336,movie,The Tango of the Widower and Its Distorting Mi...,El Tango del Viudo y Su Espejo Deformante,0,2020,\N,70,Drama
4,tt0069049,movie,The Other Side of the Wind,The Other Side of the Wind,0,2018,\N,122,Drama